Repository Leweyse/scrum-project, pull requests merged in 2021-12, with the labels that each got.

#2 Created: Products Page
  client/src/pages/ProductsPage/ProductsPage.js
  client/src/pages/ProductsPage/_ProductsPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
  client/src/style/style.scss
Labels: enhancement

#6 Created: Navbar Component
  .gitignore
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/index.js
  client/src/index.js
  client/src/style/style.css
Labels: enhancement

#11 All products routes moved out from api middleware
  api/routes/api.php
Labels: enhancement

#12 Built: Login Page
  client/src/App.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/index.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/_LoginPage.scss
  client/src/pages/ProductsPage/ProductsPage.js
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
Labels: enhancement

#13 Stylized: Login Page
  client/src/App.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/index.js
  client/src/pages/LoginPage/_LoginPage.scss
  client/src/style/layouts/_width1150.scss
  client/src/style/layouts/_width640.scss
  client/src/style/layouts/_width875.scss
  client/src/style/style.css
Labels: improvement

#15 Created: Development book
  DEVBOOK.md
  README.md
  client/src/pages/SignupPage/SignUpPage.js
  client/src/pages/SignupPage/_SignUpPage.scss
Labels: enhancement

#14 Products api
  api/app/Http/Controllers/api/ProductController.php
  api/routes/api.php
Labels: improvement

#16 Update: Development Book
  DEVBOOK.md
Labels: enhancement, improvement

#17 Update: README
  README.md
Labels: improvement

#18 Created: Single Product Page
  client/src/App.js
  client/src/pages/SingleProductPage/SingleProductPage.js
  client/src/pages/SingleProductPage/_SingleProductPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#20 Created: Landing Page and Footer
  client/package.json
  client/src/App.js
  client/src/assets/images/006d77.jpg
  client/src/assets/images/df2935.jpg
  client/src/assets/images/ead637.jpg
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Footer/_Footer.scss
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/_index.scss
  client/src/index.js
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/style/style.css
  client/yarn.lock
Labels: enhancement

#21 Created: SignUp Page
  client/src/pages/SignupPage/SignUpPage.js
  client/src/pages/SignupPage/_SignUpPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/layouts/_width640.scss
  client/src/style/layouts/_width875.scss
  client/src/style/style.css
Labels: enhancement

#22 Update: Development Book
  DEVBOOK.md
Labels: documentation

#24 Issue: #23
  client/src/components/block/index.js
  client/src/components/index.js
  client/src/pages/LandingPage/LandingPage.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#26 Client/build/page/checkout page
  DEVBOOK.md
  client/src/App.js
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Footer/_Footer.scss
  client/src/pages/CheckoutPage/CheckoutPage.js
  client/src/pages/CheckoutPage/_CheckoutPage.scss
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/pages/SignUpPage/SignUpPage.js
  client/src/pages/SignUpPage/_SignUpPage.scss
  client/src/pages/SingleProductPage/_SingleProductPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#27 Implement/page/login
  api/package-lock.json
  api/public/css/app.css
  api/public/js/app.js
  api/public/mix-manifest.json
  client/package.json
  client/src/App.js
  client/src/pages/LoginPage/LoginPage.js
  client/yarn.lock
Labels: enhancement

#28 Improved performance
  client/src/App.js
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Footer/_Footer.scss
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/components/container/StockSection/StockSection.js
  client/src/components/container/StockSection/_StockSection.scss
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/pages/ProductsPage/ProductsPage.js
  client/src/pages/SignUpPage/SignUpPage.js
  client/src/pages/SignUpPage/_SignUpPage.scss
  client/src/pages/SingleProductPage/SingleProductPage.js
  client/src/pages/SingleProductPage/_SingleProductPage.scss
  client/src/style/base/_body.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#29 Implemented: React Router DOM
  client/package.json
  client/src/App.js
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Navbar/Navbar.js
  client/yarn.lock
Labels: enhancement

#30 Updated DevBook
  DEVBOOK.md
Labels: documentation

#31 fixed responsiveness
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Footer/_Footer.scss
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/components/container/SingleProductSection/_SingleProductSection.scss
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/pages/SingleProductPage/SingleProductPage.js
  client/src/pages/SingleProductPage/_SingleProductPage.scss
  client/src/style/base/_body.scss
  client/src/style/style.css
  client/src/style/style.css.map
  node_modules/.yarn-integrity
  yarn.lock
Labels: improvement

#32 Implemented Axios in Login Page
  api/app/Http/Controllers/api/auth/LoginController.php
  api/app/Http/Kernel.php
  api/config/cors.php
  api/config/sanctum.php
  api/package.json
  api/routes/api.php
  client/.gitignore
  client/package.json
  client/src/pages/LoginPage/LoginPage.js
  client/src/services/apiClient.js
  client/yarn.lock
  yarn.lock
Labels: enhancement

#33 Responsiveness
  client/src/App.js
  client/src/components/block/Footer/_Footer.scss
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/container/StockSection/_StockSection.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#34 Created: Page Add Item
  client/src/assets/images/upload_image.jpg
  client/src/pages/AddListingPage/AddListingPage.js
  client/src/pages/AddListingPage/_AddListingPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
Labels: enhancement

#36 Update: Login Page
  client/src/pages/LoginPage/LoginPage.js
Labels: enhancement, improvement

#35 Implement API for Client: Register Page
  api/app/Http/Controllers/api/ProductController.php
  api/app/Http/Controllers/api/auth/LoginController.php
  api/app/Http/Controllers/api/auth/RegisterController.php
  client/src/App.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/SignUpPage/SignUpPage.js
Labels: enhancement

#37 Component: Product Card
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#42 Update: Development Book
  DEVBOOK.md
Labels: documentation

#43 Stylized Component: Product Card
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/style/layouts/_index.scss
  client/src/style/layouts/_width640.scss
  client/src/style/layouts/_width875.scss
  client/src/style/layouts/max/_width1200.scss
  client/src/style/layouts/max/_width640.scss
  client/src/style/layouts/max/_width875.scss
  client/src/style/layouts/min/_width1500.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#44 Implemented API: Route based on id
  client/src/App.js
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/container/StockSection/StockSection.js
Labels: enhancement

#45 Big update
  README.md
  client/public/index.html
  client/src/components/block/Footer/Footer.js
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/SVGs/UserIconSVG/UserIconSVG.js
  client/src/components/block/SVGs/UserIconSVG/_UserIconSvg.scss
  client/src/components/block/_index.scss
  client/src/components/container/LoginSection/LoginSection.js
  client/src/components/container/LoginSection/_LoginSection.scss
  client/src/components/container/_index.scss
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/_LoginPage.scss
  client/src/style/style.css
Labels: improvement

#47 API: Stats implemented
  api/app/Http/Controllers/api/ProductController.php
  api/app/Models/Category.php
  api/app/Models/Order.php
  api/app/Models/OrderItem.php
  api/app/Models/Product.php
  api/app/Models/Stat.php
  api/database/migrations/2021_12_21_084312_create_products_table.php
  api/database/migrations/2021_12_21_084322_create_order_items_table.php
  api/routes/api.php
Labels: enhancement

#49 Component: Navbar
  client/src/components/block/LogoutButton/LogoutButton.js
  client/src/components/block/LogoutButton/_LogoutButton.scss
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#50 Built: Loading Spinner Component
  client/src/components/block/Loading/Spinner/Spinner.js
  client/src/components/block/Loading/Spinner/_Spinner.scss
  client/src/components/block/Loading/_index.scss
  client/src/components/block/Loading/index.js
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/SVGs/_index.scss
  client/src/components/block/SVGs/index.js
  client/src/components/block/_index.scss
  client/src/components/block/index.js
Labels: enhancement

#51 Implemented API: Stock Section
  client/src/components/container/StockSection/StockSection.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#52 Component: Login
  client/src/components/container/LoginSection/LoginSection.js
Labels: improvement

#56 Page: Reset Password
  client/src/App.js
  client/src/pages/ResetPasswordPage/ResetPasswordPage.js
  client/src/pages/ResetPasswordPage/_ResetPasswordPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#57 Updated API: Products
  api/app/Http/Controllers/api/ProductController.php
Labels: improvement

#59 Implemented API: Logout Button
  client/src/components/block/LogoutButton/LogoutButton.js
  client/src/components/container/LoginSection/LoginSection.js
Labels: enhancement, improvement

#60 API: Products Controller
  api/app/Http/Controllers/api/ProductController.php
Labels: enhancement, improvement

#63 Refactored: Landing Page
  client/src/assets/slidesdata/SlidesData.js
  client/src/components/block/Carousel/Carousel.js
  client/src/components/block/Carousel/_Carousel.scss
  client/src/components/block/SVGs/ButtonLeftSVG/ButtonLeftSVG.js
  client/src/components/block/SVGs/ButtonLeftSVG/_ButtonLeftSVG.scss
  client/src/components/block/SVGs/ButtonRightSVG/ButtonRightSVG.js
  client/src/components/block/SVGs/ButtonRightSVG/_ButtonRightSVG.scss
  client/src/components/block/SVGs/index.js
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/index.js
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement, readability

#61 API: User
  api/app/Http/Controllers/api/ProductController.php
  api/app/Http/Controllers/api/UserController.php
  api/routes/api.php
Labels: enhancement, improvement

#64 Created: Cart Page
  client/src/App.js
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/block/ProductRow/_ProductRow.scss
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/container/CartSection/CartSection.js
  client/src/components/container/CartSection/_CartSection.scss
  client/src/components/container/StockSection/StockSection.js
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/CartPage/CartPage.js
  client/src/pages/CartPage/_CartPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/base/_body.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement
