Repository Leweyse/scrum-project, pull requests merged in 2022-01, with the labels that each got.

#69 Implement API Response: Stock Section
  api/app/Http/Controllers/api/ProductController.php
  client/src/App.js
  client/src/assets/slidesdata/SlidesData.js
  client/src/components/block/Loading/Spinner/Spinner.js
  client/src/components/block/LogoutButton/LogoutButton.js
  client/src/components/block/LogoutButton/_LogoutButton.scss
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/components/container/CartSection/_CartSection.scss
  client/src/components/container/LoginSection/LoginSection.js
  client/src/components/container/LoginSection/_LoginSection.scss
  client/src/components/container/StockSection/StockSection.js
  client/src/components/container/StockSection/_StockSection.scss
  client/src/index.js
  client/src/pages/ResetPasswordPage/ResetPasswordPage.js
  client/src/pages/ResetPasswordPage/_ResetPasswordPage.scss
  client/src/pages/SignUpPage/SignUpPage.js
  client/src/style/base/_button.scss
  client/src/style/base/_index.scss
  client/src/style/base/_main.scss
  client/src/style/layouts/max/_width1200.scss
  client/src/style/layouts/max/_width640.scss
  client/src/style/layouts/max/_width875.scss
  client/src/style/layouts/min/_width1500.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#68 Build/profile
  api/app/Http/Controllers/api/auth/PasswordController.php
  api/app/Models/User.php
  api/app/Notifications/ResetPasswordNotification.php
  api/composer.json
  api/composer.lock
  api/config/app.php
  api/config/image.php
  api/routes/api.php
Labels: enhancement, improvement

#70 Update: Development Book
  DEVBOOK.md
Labels: documentation

#71 Improved readability
  client/src/components/container/LandingSection/LandingSection.js
  client/src/components/container/LandingSection/_LandingSection.scss
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/LandingPage/LandingPage.js
  client/src/pages/LandingPage/_LandingPage.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: readability

#72 Improved readability
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/components/container/SignUpSection/_SignUpSection.scss
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/SignUpPage/SignUpPage.js
  client/src/pages/SignUpPage/_SignUpPage.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: readability

#74 Improved readability
  client/src/components/container/ProfileSection/ProfileSection.js
  client/src/components/container/ProfileSection/_ProfileSection.scss
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/ProfilePage/ProfilePage.js
  client/src/pages/ProfilePage/_ProfilePage.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: readability

#75 improved readability
  client/src/components/container/CheckoutSection/CheckoutSection.js
  client/src/components/container/CheckoutSection/_CheckoutSection.scss
  client/src/components/container/_index.scss
  client/src/components/container/index.js
  client/src/components/index.js
  client/src/pages/CheckoutPage/CheckoutPage.js
  client/src/pages/CheckoutPage/_CheckoutPage.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: readability

#80 Single Product Page: Load product from API
  client/package.json
  client/src/assets/slidesdata/SlidesData.js
  client/src/components/block/Carousel/Carousel.js
  client/src/components/block/Carousel/SlidesData.js
  client/src/components/block/Carousel/_Carousel.scss
  client/src/components/block/Navbar/_Navbar.scss
  client/src/components/block/SlideElement/SlideElement.js
  client/src/components/block/SlideElement/_SlideElement.scss
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/index.js
  client/src/pages/ProfilePage/ProfilePage.js
  client/src/pages/ProfilePage/_ProfilePage.scss
  client/src/pages/SingleProductPage/SingleProductPage.js
  client/src/style/style.css
  client/src/style/style.css.map
  client/yarn.lock
Labels: enhancement

#81 User Profile: Edit Details Form
  client/src/components/container/ListingSection/ListingSection.js
  client/src/components/container/ProfileSection/ProfileSection.js
  client/src/components/container/ProfileSection/_ProfileSection.scss
  client/src/pages/ProfilePage/ProfilePage.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#85 Style: Check Box - Terms and Conditions
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/components/container/SignUpSection/_SignUpSection.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#88 Category crud api applied
  api/app/Http/Controllers/api/CategoryController.php
  api/app/Http/Controllers/api/ProductController.php
  api/app/Models/Category.php
  api/routes/api.php
Labels: enhancement

#89 implemented preliminary stats graph for displaying product price changes
  client/src/components/block/Navbar/Navbar.js
  client/src/components/block/StatsChart/StatsChart.js
  client/src/components/block/StatsChart/_StatsChart.scss
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/components/container/SignUpSection/_SignUpSection.scss
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/components/container/SingleProductSection/_SingleProductSection.scss
  client/src/components/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#91 resolved login error message display issue
  client/src/components/container/LoginSection/LoginSection.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: bug

#92 Solved: Register issue with terms checkbox
  client/src/components/container/SignUpSection/SignUpSection.js
Labels: bug

#93 added return/cancellation page with style without api
  client/src/App.js
  client/src/pages/ReturnCancellationPage/ReturnCancellationPage.js
  client/src/pages/ReturnCancellationPage/_ReturnCancellationPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#95 General Order api created without cart items
  api/app/Http/Controllers/Test/FakeStatController.php
  api/app/Http/Controllers/api/OrderController.php
  api/app/Models/Order.php
  api/database/migrations/2021_12_21_084318_create_orders_table.php
  api/routes/api.php
Labels: enhancement

#96 minor formatting
  api/app/Http/Controllers/Test/FakeStatController.php
  client/src/components/block/StatsChart/StatsChart.js
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/components/container/SingleProductSection/_SingleProductSection.scss
  client/src/components/container/StockSection/StockSection.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#97 Api/product
  api/app/Http/Controllers/api/ProductController.php
  api/routes/api.php
Labels: enhancement, improvement

#98 Implement Logic: Cart Page
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/container/CartSection/CartSection.js
  client/src/components/container/SingleProductSection/SingleProductSection.js
Labels: enhancement

#99 Product Image added to create and update product
  api/app/Http/Controllers/api/ImageController.php
  api/app/Http/Controllers/api/ProductController.php
  api/routes/api.php
  api/storage/app/public/.gitignore
  client/src/components/container/ListingSection/ListingSection.js
Labels: enhancement

#100 Api for adding, updating and removing from cart is added
  api/app/Http/Controllers/api/CartController.php
  api/app/Http/Controllers/api/OrderController.php
  api/composer.json
  api/composer.lock
  api/config/cart.php
  api/routes/api.php
Labels: enhancement

#103 Update: Development Book
  DEVBOOK.md
Labels: documentation

#102 Implement: Private/Auth route
  client/src/App.js
  client/src/components/block/Navbar/Navbar.js
  client/src/pages/ProfilePage/ProfilePage.js
  client/src/services/Context.js
  client/src/services/PrivateRoutes.js
Labels: enhancement

#101 Build/cart
  api/app/Http/Controllers/api/CartController.php
  api/routes/api.php
  api/routes/web.php
  client/src/assets/images/default.jpg
  client/src/assets/images/default_product.jpg
  client/src/components/block/AddToCartBtn/AddToCartBtn.js
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/block/index.js
  client/src/components/container/CartSection/CartSection.js
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/pages/index.js
Labels: bug

#105 Client/build/pages/terms conditions page
  client/src/App.js
  client/src/components/container/ListingSection/ListingSection.js
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/pages/TermsConditionsPage/TermsConditionsPage.js
  client/src/pages/TermsConditionsPage/_TermsConditionsPage.scss
  client/src/pages/_index.scss
  client/src/pages/index.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#107 bunch of stuff
  api/app/Models/Product.php
  api/database/factories/ProductFactory.php
  api/routes/web.php
  client/src/components/block/Carousel/SlidesData.js
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/container/CartSection/CartSection.js
  client/src/components/container/CartSection/_CartSection.scss
  client/src/components/container/ListingSection/ListingSection.js
  client/src/components/container/LoginSection/LoginSection.js
  client/src/components/container/ProfileSection/ProfileSection.js
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/style/style.css
  client/src/style/style.css.map
  client/src/style/style.scss
  client/src/style/utils/_index.scss
Labels: improvement

#109 Orderging system implementem along with cart
  api/app/Http/Controllers/api/OrderController.php
  api/database/migrations/2021_12_21_084318_create_orders_table.php
  api/routes/api.php
  api/routes/web.php
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/container/CartSection/CartSection.js
  client/src/components/container/CheckoutSection/CheckoutSection.js
  client/src/components/container/SignUpSection/SignUpSection.js
  client/src/pages/EditListingPage/EditListingPage.js
Labels: enhancement

#112 profile editing successfully impletemented
  client/src/components/container/ProfileSection/ProfileSection.js
Labels: enhancement

#111 Solved issues related to Listings Page
  client/src/components/block/AddToCartBtn/AddToCartBtn.js
  client/src/components/block/ProductCard/ProductCard.js
  client/src/components/block/_index.scss
  client/src/components/container/ListingSection/ListingSection.js
  client/src/components/container/ListingSection/_ListingSection.scss
  client/src/components/container/ProfileSection/ProfileSection.js
  client/src/components/container/SingleProductSection/SingleProductSection.js
  client/src/components/container/SingleProductSection/_SingleProductSection.scss
  client/src/components/container/StockSection/StockSection.js
  client/src/style/base/_button.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#115 Added routes for landing page
  client/src/components/block/Carousel/SlidesData.js
  client/src/components/block/Carousel/_Carousel.scss
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/components/block/SlideElement/SlideElement.js
  client/src/components/block/SlideElement/_SlideElement.scss
  client/src/components/container/StockSection/_StockSection.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#117 search kinda working
  client/src/components/block/Navbar/Navbar.js
  client/src/pages/SearchResultPage/SearchResultPage.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement

#118 solved issue
  client/src/components/block/Navbar/Navbar.js
  client/src/components/container/CheckoutSection/CheckoutSection.js
  client/src/components/container/CheckoutSection/_CheckoutSection.scss
  client/src/style/style.css
Labels: enhancement

#124 Solved Responsive issue: Product Card
  client/src/components/block/ProductCard/_ProductCard.scss
  client/src/components/container/StockSection/_StockSection.scss
  client/src/style/style.css
  client/src/style/style.css.map
Labels: improvement

#125 Solved: Listing Section
  client/src/components/container/ListingSection/ListingSection.js
  client/src/pages/EditListingPage/EditListingPage.js
Labels: enhancement, readability

#127 Extra code: Listing pages
  client/src/App.js
  client/src/components/block/Pagination/Pagination.js
  client/src/components/block/Pagination/_Pagination.scss
  client/src/components/block/_index.scss
  client/src/components/block/index.js
  client/src/components/container/StockSection/StockSection.js
  client/src/components/container/StockSection/_StockSection.scss
  client/src/components/index.js
  client/src/pages/SearchResultPage/SearchResultPage.js
  client/src/style/style.css
  client/src/style/style.css.map
Labels: enhancement, improvement

#128 Cart Page: Update total
  client/src/components/block/ProductRow/ProductRow.js
  client/src/components/container/CartSection/CartSection.js
Labels: enhancement

#130 Updated: api/readme
  api/README.md
Labels: documentation
